### ISSUE TITLE
Issues using snapshots with `expect.it()` in a nested structure

### ISSUE THREAD

**Issue by alexjeffburke** [unexpectedjs/unexpected-snapshot#57]
I had a case where I tried to check that a function was called with an object that contained a key whose value was a snapshotted string, so I used one of the "satisfying" assertions in `-sinon`. The following is a simplified reproduction case:

```js
const expect = require("unexpected")
  .clone()
  .use(require("unexpected-snapshot"));

const makeSomeStuff = () => "foo bar baz";

it("should work", () => {
  expect(
    [
      {
        stuff: makeSomeStuff()
      }
    ],
    "to satisfy",
    [
      {
        stuff: expect.it("to equal snapshot")
      }
    ]
  );
});
```

Running the block as-is, I receive the following `TypeError`:
```
     TypeError: Cannot read property 'replace' of undefined
      at fixUnexpected (node_modules/unexpected-snapshot/lib/applyFixes.js:87:62)
      at Traverser.enter [as _enter] (node_modules/unexpected-snapshot/lib/applyFixes.js:209:26)
```

If I force the insertion point by modifying the expect.it to read `expect.it('to equal snapshot', '')` it gets further, but the injection of the snapshot removes the spec structure nesting on the RHS and the result is as follows:

```
it("should work", () => {
  expect(
    [
      {
        stuff: makeSomeStuff()
      }
    ],
    "to satisfy",
    expect.unindent`
      foo bar baz
      baz bar foo
    `
  );
});
```

**Comment by papandreou** [comment]
unexpected-snapshot does not support `expect.it` at the moment. It'll be rather tricky, so we decided to leave it out initially. Would be nice if it failed a bit more gracefully, though.

**Comment by papandreou** [comment]
I added a nicer warning in 1.0.2.

**Comment by alexjeffburke** [comment]
@papandreou I confess that I wasn't aware this wasn't intended to work per se, and choosing to show a clear message in this case is a really good shout - keep the user informed etc.

I'll try the change in situ so I get some perspective on encountering it in person but otherwise I think we can say this is addressed. And we can already revisit if/when we tackle it.
